url: https://danielsaavedra.info
enforce_ssl: danielsaavedra.info
title: Daniel Saavedra
subtitle:
author: Daniel Saavedra
simlpe_search: http://google.com/search

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: "UA-47788797-1"

# Facebook Like
facebook_like: false